### ISSUE TITLE
No Recipe to Craft Waxed Planks

### ISSUE THREAD

**Issue by Morabert** [StephenBarnes/Waxed-Wood#1] opened 2021-11-08 16:43 UTC
There's no way to craft waxed planks
there's also no recipe to craft waxed logs direct
![fdgdfgs](https://user-images.githubusercontent.com/36409264/140782721-4363a87a-5d07-4d24-a27e-1d5784328619.JPG)
![kokdd](https://user-images.githubusercontent.com/36409264/140782727-a6e34eca-1cb2-4a3b-810f-86381691ca7d.JPG)
![gggg](https://user-images.githubusercontent.com/36409264/140782728-fd81e358-25e6-4fff-8840-5305cbea175a.JPG)
ly

**Comment by StephenBarnes** [comment] 2021-11-11 02:34
Looks like it was caused by multiple recipes being generated with the same name, so they overwrote each other. Fixed in 1.1.

**Closed as completed by StephenBarnes** 2021-11-11 02:34 UTC
